### ISSUE TITLE
How to configure the settings of aTilt

### ISSUE THREAD

**Issue by tuminzee** [vinicius91/angular-tilt#2]
Please demonstrate how to modify the settings of aTilt
I tried using `[tiltSettings]="tiltSettings"`  but I wasn't able to get it right.

_Thanks in advance._

**Comment by vendipala** [comment]
Same Problem here.
I tested a variety of combinations with the vanilla-tilt.js Options, like [tiltSettings]="scale: 1.1" but none of them work.

An example would be nice.

**Comment by the-javapocalypse** [comment]
After digging down in the code, this is the interface for tilt settings I suppose
```
export interface VanillaTiltSettings {
    reverse?: boolean;
    max?: number;
    perspective?: number;
    scale?: number;
    speed?: number;
    transition?: boolean;
    axis?: string;
    reset?: boolean;
    easing?: string;
    glare?: boolean;
    "max-glare"?: number;
    "glare-prerender"?: boolean;
    "mouse-event-element"?: string;
    gyroscope?: boolean;
    gyroscopeMaxAngleX?: number;
    gyroscopeMinAngleY?: number;
    gyroscopeMaxAngleY?: number;
}
```
